/* prettier-ignore */
/*
 *    _____ _     _____ _   _ _   _
 *   / ____| |   |  ___| \ | | \ | |
 *  | |  __| |   | |__ |  \| |  \| |
 *  | | |_ | |   |  __|| . ` | . ` |
 *  | |__| | |___| |___| |\  | |\  |
 *   \_____|_____|_____|_| \_|_| \_|
 *
 *  kanji-data.js — JLPT N5 kanji data (112 characters) with meanings and readings
 *  Glenn's Japanese Trainer
 */

const KanjiData = {
  numbers: [
    { kanji: "一", meaning: ["one"], meaningNo: ["en"], onyomi: ["ichi"], kunyomi: ["hito(tsu)"] },
    { kanji: "二", meaning: ["two"], meaningNo: ["to"], onyomi: ["ni"], kunyomi: ["futa(tsu)"] },
    { kanji: "三", meaning: ["three"], meaningNo: ["tre"], onyomi: ["san"], kunyomi: ["mi(ttsu)"] },
    { kanji: "四", meaning: ["four"], meaningNo: ["fire"], onyomi: ["shi"], kunyomi: ["yo(ttsu)", "yon"] },
    { kanji: "五", meaning: ["five"], meaningNo: ["fem"], onyomi: ["go"], kunyomi: ["itsu(tsu)"] },
    { kanji: "六", meaning: ["six"], meaningNo: ["seks"], onyomi: ["roku"], kunyomi: ["mu(ttsu)", "mui"] },
    { kanji: "七", meaning: ["seven"], meaningNo: ["sju", "syv"], onyomi: ["shichi"], kunyomi: ["nana(tsu)", "nana"] },
    { kanji: "八", meaning: ["eight"], meaningNo: ["åtte"], onyomi: ["hachi"], kunyomi: ["ya(ttsu)", "you"] },
    { kanji: "九", meaning: ["nine"], meaningNo: ["ni"], onyomi: ["kyuu", "ku"], kunyomi: ["kokono(tsu)"] },
    { kanji: "十", meaning: ["ten"], meaningNo: ["ti"], onyomi: ["juu"], kunyomi: ["tou", "too"] },
    { kanji: "百", meaning: ["hundred"], meaningNo: ["hundre"], onyomi: ["hyaku"], kunyomi: [] },
    { kanji: "千", meaning: ["thousand"], meaningNo: ["tusen"], onyomi: ["sen"], kunyomi: ["chi"] },
    { kanji: "万", meaning: ["ten thousand"], meaningNo: ["ti tusen"], onyomi: ["man"], kunyomi: [] },
    { kanji: "億", meaning: ["hundred million"], meaningNo: ["hundre millioner"], onyomi: ["oku"], kunyomi: [] },
  ],
  time: [
    { kanji: "日", meaning: ["day", "sun"], meaningNo: ["dag", "sol"], onyomi: ["nichi", "jitsu"], kunyomi: ["hi", "ka"] },
    { kanji: "週", meaning: ["week"], meaningNo: ["uke"], onyomi: ["shuu"], kunyomi: [] },
    { kanji: "月", meaning: ["month", "moon"], meaningNo: ["måned", "måne"], onyomi: ["getsu", "gatsu"], kunyomi: ["tsuki"] },
    { kanji: "年", meaning: ["year"], meaningNo: ["år"], onyomi: ["nen"], kunyomi: ["toshi"] },
    { kanji: "時", meaning: ["time", "hour"], meaningNo: ["tid", "time"], onyomi: ["ji"], kunyomi: ["toki"] },
    { kanji: "間", meaning: ["interval"], meaningNo: ["intervall", "mellomrom"], onyomi: ["kan"], kunyomi: ["aida", "ma"] },
    { kanji: "分", meaning: ["minute", "part"], meaningNo: ["minutt", "del"], onyomi: ["bun", "fun", "bu"], kunyomi: ["wa(karu)"] },
    { kanji: "午", meaning: ["noon"], meaningNo: ["middag"], onyomi: ["go"], kunyomi: [] },
    { kanji: "前", meaning: ["before"], meaningNo: ["før", "foran"], onyomi: ["zen"], kunyomi: ["mae"] },
    { kanji: "後", meaning: ["after"], meaningNo: ["etter"], onyomi: ["go", "kou"], kunyomi: ["ato", "ushi(ro)"] },
    { kanji: "今", meaning: ["now"], meaningNo: ["nå"], onyomi: ["kon"], kunyomi: ["ima"] },
    { kanji: "先", meaning: ["previous"], meaningNo: ["forrige"], onyomi: ["sen"], kunyomi: ["saki"] },
    { kanji: "来", meaning: ["next", "come"], meaningNo: ["neste", "komme"], onyomi: ["rai"], kunyomi: ["ku(ru)"] },
    { kanji: "毎", meaning: ["every"], meaningNo: ["hver"], onyomi: ["mai"], kunyomi: ["goto"] },
  ],
  people: [
    { kanji: "人", meaning: ["person"], meaningNo: ["person", "menneske"], onyomi: ["jin", "nin"], kunyomi: ["hito"] },
    { kanji: "男", meaning: ["man"], meaningNo: ["mann"], onyomi: ["dan", "nan"], kunyomi: ["otoko"] },
    { kanji: "女", meaning: ["woman"], meaningNo: ["kvinne"], onyomi: ["jo"], kunyomi: ["onna"] },
    { kanji: "子", meaning: ["child"], meaningNo: ["barn"], onyomi: ["shi"], kunyomi: ["ko"] },
    { kanji: "母", meaning: ["mother"], meaningNo: ["mor"], onyomi: ["bo"], kunyomi: ["haha"] },
    { kanji: "父", meaning: ["father"], meaningNo: ["far"], onyomi: ["fu"], kunyomi: ["chichi"] },
    { kanji: "友", meaning: ["friend"], meaningNo: ["venn"], onyomi: ["yuu"], kunyomi: ["tomo"] },
    { kanji: "本", meaning: ["book", "origin"], meaningNo: ["bok", "opprinnelse"], onyomi: ["hon"], kunyomi: ["moto"] },
    { kanji: "気", meaning: ["spirit"], meaningNo: ["and", "energi"], onyomi: ["ki"], kunyomi: [] },
    { kanji: "生", meaning: ["life"], meaningNo: ["liv"], onyomi: ["sei", "shou"], kunyomi: ["i(kiru)", "u(mareru)"] },
    { kanji: "車", meaning: ["car"], meaningNo: ["bil"], onyomi: ["sha"], kunyomi: ["kuruma"] },
    { kanji: "語", meaning: ["language"], meaningNo: ["språk"], onyomi: ["go"], kunyomi: ["kata(ru)"] },
    { kanji: "耳", meaning: ["ear"], meaningNo: ["øre"], onyomi: ["ji"], kunyomi: ["mimi"] },
    { kanji: "手", meaning: ["hand"], meaningNo: ["hand"], onyomi: ["shu"], kunyomi: ["te"] },
    { kanji: "足", meaning: ["foot"], meaningNo: ["fot"], onyomi: ["soku"], kunyomi: ["ashi", "ta(su)"] },
    { kanji: "目", meaning: ["eye"], meaningNo: ["øye"], onyomi: ["moku"], kunyomi: ["me"] },
    { kanji: "口", meaning: ["mouth"], meaningNo: ["munn"], onyomi: ["kou"], kunyomi: ["kuchi"] },
    { kanji: "店", meaning: ["shop"], meaningNo: ["butikk"], onyomi: ["ten"], kunyomi: ["mise"] },
    { kanji: "駅", meaning: ["station"], meaningNo: ["stasjon"], onyomi: ["eki"], kunyomi: [] },
    { kanji: "道", meaning: ["street", "road"], meaningNo: ["gate", "vei"], onyomi: ["dou"], kunyomi: ["michi"] },
    { kanji: "国", meaning: ["country"], meaningNo: ["land"], onyomi: ["koku"], kunyomi: ["kuni"] },
    { kanji: "学", meaning: ["study"], meaningNo: ["studere", "lære"], onyomi: ["gaku"], kunyomi: ["mana(bu)"] },
    { kanji: "校", meaning: ["school"], meaningNo: ["skole"], onyomi: ["kou"], kunyomi: [] },
    { kanji: "名", meaning: ["name"], meaningNo: ["navn"], onyomi: ["mei", "myou"], kunyomi: ["na"] },
    { kanji: "円", meaning: ["yen", "circle"], meaningNo: ["yen", "sirkel"], onyomi: ["en"], kunyomi: ["maru(i)"] },
    { kanji: "半", meaning: ["half"], meaningNo: ["halv"], onyomi: ["han"], kunyomi: ["naka(ba)"] },
    { kanji: "全", meaning: ["all"], meaningNo: ["alle", "alt"], onyomi: ["zen"], kunyomi: ["matta(ku)", "sube(te)"] },
    { kanji: "何", meaning: ["what"], meaningNo: ["hva"], onyomi: ["ka"], kunyomi: ["nan", "nani"] },
  ],
  nature: [
    { kanji: "火", meaning: ["fire"], meaningNo: ["ild", "brann"], onyomi: ["ka"], kunyomi: ["hi"] },
    { kanji: "水", meaning: ["water"], meaningNo: ["vann"], onyomi: ["sui"], kunyomi: ["mizu"] },
    { kanji: "木", meaning: ["tree"], meaningNo: ["tre"], onyomi: ["moku"], kunyomi: ["ki"] },
    { kanji: "金", meaning: ["money", "gold"], meaningNo: ["penger", "gull"], onyomi: ["kin"], kunyomi: ["kane"] },
    { kanji: "土", meaning: ["earth"], meaningNo: ["jord"], onyomi: ["do", "to"], kunyomi: ["tsuchi"] },
    { kanji: "海", meaning: ["sea"], meaningNo: ["hav", "sjø"], onyomi: ["kai"], kunyomi: ["umi"] },
    { kanji: "川", meaning: ["river"], meaningNo: ["elv"], onyomi: ["sen"], kunyomi: ["kawa"] },
    { kanji: "山", meaning: ["mountain"], meaningNo: ["fjell"], onyomi: ["san"], kunyomi: ["yama"] },
    { kanji: "花", meaning: ["flower"], meaningNo: ["blomst"], onyomi: ["ka"], kunyomi: ["hana"] },
    { kanji: "天", meaning: ["heaven"], meaningNo: ["himmel"], onyomi: ["ten"], kunyomi: ["ame", "ama"] },
    { kanji: "空", meaning: ["sky", "empty"], meaningNo: ["himmel", "tom"], onyomi: ["kuu"], kunyomi: ["sora", "a(keru)"] },
    { kanji: "晴", meaning: ["sunny"], meaningNo: ["sol", "klarvær"], onyomi: ["sei"], kunyomi: ["ha(re)"] },
    { kanji: "雨", meaning: ["rain"], meaningNo: ["regn"], onyomi: ["u"], kunyomi: ["ame"] },
    { kanji: "雪", meaning: ["snow"], meaningNo: ["snø"], onyomi: ["setsu"], kunyomi: ["yuki"] },
    { kanji: "雲", meaning: ["cloud"], meaningNo: ["sky", "skye"], onyomi: ["un"], kunyomi: ["kumo"] },
    { kanji: "風", meaning: ["wind"], meaningNo: ["vind"], onyomi: ["fuu"], kunyomi: ["kaze"] },
    { kanji: "電", meaning: ["electricity"], meaningNo: ["elektrisitet", "strøm"], onyomi: ["den"], kunyomi: [] },
    { kanji: "外", meaning: ["outside"], meaningNo: ["utenfor", "ute"], onyomi: ["gai"], kunyomi: ["soto", "hazu(reru)"] },
    { kanji: "内", meaning: ["inside"], meaningNo: ["innenfor", "inne"], onyomi: ["nai"], kunyomi: ["uchi"] },
    { kanji: "上", meaning: ["above"], meaningNo: ["over", "opp"], onyomi: ["jou"], kunyomi: ["ue", "a(geru)"] },
    { kanji: "下", meaning: ["below"], meaningNo: ["under", "ned"], onyomi: ["ka", "ge"], kunyomi: ["shita", "ku(daru)"] },
    { kanji: "右", meaning: ["right"], meaningNo: ["høyre"], onyomi: ["yuu"], kunyomi: ["migi"] },
    { kanji: "左", meaning: ["left"], meaningNo: ["venstre"], onyomi: ["sa"], kunyomi: ["hidari"] },
    { kanji: "中", meaning: ["middle"], meaningNo: ["midt", "midten"], onyomi: ["chuu", "juu"], kunyomi: ["naka"] },
    { kanji: "北", meaning: ["north"], meaningNo: ["nord"], onyomi: ["hoku"], kunyomi: ["kita"] },
    { kanji: "西", meaning: ["west"], meaningNo: ["vest"], onyomi: ["sei", "sai"], kunyomi: ["nishi"] },
    { kanji: "東", meaning: ["east"], meaningNo: ["øst"], onyomi: ["tou"], kunyomi: ["higashi"] },
    { kanji: "南", meaning: ["south"], meaningNo: ["sør"], onyomi: ["nan"], kunyomi: ["minami"] },
  ],
  verbs: [
    { kanji: "見", meaning: ["see"], meaningNo: ["se"], onyomi: ["ken"], kunyomi: ["mi(ru)"] },
    { kanji: "聞", meaning: ["hear"], meaningNo: ["høre"], onyomi: ["mon", "bun"], kunyomi: ["ki(ku)"] },
    { kanji: "書", meaning: ["write"], meaningNo: ["skrive"], onyomi: ["sho"], kunyomi: ["ka(ku)"] },
    { kanji: "言", meaning: ["say"], meaningNo: ["si", "snakke"], onyomi: ["gen"], kunyomi: ["i(u)"] },
    { kanji: "話", meaning: ["talk"], meaningNo: ["prate", "samtale"], onyomi: ["wa"], kunyomi: ["hanashi", "hana(su)"] },
    { kanji: "読", meaning: ["read"], meaningNo: ["lese"], onyomi: ["doku"], kunyomi: ["yo(mu)"] },
    { kanji: "行", meaning: ["go"], meaningNo: ["gå", "dra"], onyomi: ["kou"], kunyomi: ["i(ku)", "okona(u)"] },
    { kanji: "買", meaning: ["buy"], meaningNo: ["kjøpe"], onyomi: ["bai"], kunyomi: ["ka(u)"] },
    { kanji: "出", meaning: ["exit"], meaningNo: ["ut", "utgang"], onyomi: ["shutsu"], kunyomi: ["de(ru)", "da(su)"] },
    { kanji: "入", meaning: ["enter"], meaningNo: ["inn", "inngang"], onyomi: ["nyuu"], kunyomi: ["hai(ru)", "i(reru)"] },
    { kanji: "食", meaning: ["eat"], meaningNo: ["spise"], onyomi: ["shoku"], kunyomi: ["ta(beru)"] },
    { kanji: "飲", meaning: ["drink"], meaningNo: ["drikke"], onyomi: ["in"], kunyomi: ["no(mu)"] },
    { kanji: "休", meaning: ["rest"], meaningNo: ["hvile"], onyomi: ["kyuu"], kunyomi: ["yasu(mu)", "yasu(mi)"] },
    { kanji: "会", meaning: ["meet"], meaningNo: ["møte", "treffe"], onyomi: ["kai"], kunyomi: ["a(u)"] },
  ],
  adjectives: [
    { kanji: "多", meaning: ["many", "a lot"], meaningNo: ["mange", "mye"], onyomi: ["ta"], kunyomi: ["oo(i)"] },
    { kanji: "少", meaning: ["few", "a little"], meaningNo: ["få", "litt"], onyomi: ["shou"], kunyomi: ["suko(shi)", "suku(nai)"] },
    { kanji: "古", meaning: ["old"], meaningNo: ["gammel"], onyomi: ["ko"], kunyomi: ["furu(i)"] },
    { kanji: "新", meaning: ["new"], meaningNo: ["ny"], onyomi: ["shin"], kunyomi: ["atara(shii)"] },
    { kanji: "大", meaning: ["big"], meaningNo: ["stor"], onyomi: ["dai", "tai"], kunyomi: ["oo(kii)"] },
    { kanji: "小", meaning: ["small"], meaningNo: ["liten"], onyomi: ["shou"], kunyomi: ["chii(sai)", "ko"] },
    { kanji: "長", meaning: ["long", "leader"], meaningNo: ["lang", "leder"], onyomi: ["chou"], kunyomi: ["naga(i)"] },
    { kanji: "短", meaning: ["short"], meaningNo: ["kort"], onyomi: ["tan"], kunyomi: ["mijika(i)"] },
    { kanji: "遠", meaning: ["far"], meaningNo: ["langt", "fjern"], onyomi: ["en"], kunyomi: ["too(i)"] },
    { kanji: "近", meaning: ["near"], meaningNo: ["nær"], onyomi: ["kin", "kon"], kunyomi: ["chika(i)"] },
    { kanji: "白", meaning: ["white"], meaningNo: ["hvit"], onyomi: ["haku"], kunyomi: ["shiro", "shiro(i)"] },
    { kanji: "黒", meaning: ["black"], meaningNo: ["svart"], onyomi: ["koku"], kunyomi: ["kuro", "kuro(i)"] },
    { kanji: "高", meaning: ["expensive", "high"], meaningNo: ["dyr", "høy"], onyomi: ["kou"], kunyomi: ["taka(i)"] },
    { kanji: "安", meaning: ["cheap", "safety"], meaningNo: ["billig", "sikkerhet"], onyomi: ["an"], kunyomi: ["yasu(i)"] },
  ],
};
